# # name: evole
# # description: "A new Flutter project."
# # publish_to: 'none'

# # version: 1.0.0+1

# # environment:
# #   sdk: '>=3.9.2 <4.0.0' # Updated format for Dart SDK constraint

# # dependencies:
# #   flutter:
# #     sdk: flutter
# #   cupertino_icons: ^1.0.8
# #   firebase_core: ^3.7.1
# #   firebase_auth: ^5.1.2
# #   google_sign_in: ^6.2.1
# #   flutter_svg: ^2.2.3

# # dev_dependencies:
# #   flutter_test:
# #     sdk: flutter
# #   flutter_lints: ^5.0.0


# #   flutter:
# #   uses-material-design: true

# #   assets:
# #     - assets/images/search1.png
# #     - assets/icons/


# name: evole
# description: "A new Flutter project."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: '>=3.5.0 <4.0.0'   # Safe range for Flutter 3.24+

# dependencies:
#   flutter:
#     sdk: flutter

#   cupertino_icons: ^1.0.8
#   flutter_svg: ^2.0.10+1
#   firebase_core: ^3.7.1
#   firebase_auth: ^5.3.1
#   google_sign_in: ^6.2.1

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^5.0.0

# # ←←← ONLY ONE flutter: section allowed here (top-level)
# flutter:
#   uses-material-design: true

#   assets:
#     - assets/images/search1.png
#     - assets/icons/          # All your Figma SVGs will load perfectly


# # For information on the generic Dart part of this file, see the
# # following page: https://dart.dev/tools/pub/pubspec

# # The following section is specific to Flutter packages.
# flutter: # <--- This is the only top-level 'flutter:' key

#   # The following line ensures that the Material Icons font is
#   # included with your application, so that you can use the icons in
#   # the material Icons class.
#   uses-material-design: true # Indented 2 spaces from 'flutter'

#   # To add assets to your application, add an assets section, like this:
#   assets: # Indented 2 spaces from 'flutter'
#     - assets/images/search1.png




# name: evole
# description: "A new Flutter project."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: '>=3.5.0 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter   # ← Only one time, correct syntax

#   cupertino_icons: ^1.0.8
#   flutter_svg: ^2.0.10+1
#   firebase_core: ^3.7.1
#   firebase_auth: ^5.3.1
#   google_sign_in: ^6.2.1

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true

#   assets:
#     - assets/images/search1.png
#     - assets/icons/          # All your Figma SVGs will load automatically



name: evole
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.7.1
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_functions: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/search1.png
    - assets/icons/
    - assets/fonts/  # Added fonts directory

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700